version: "3.9"
services:
  web:
    build: .
    container_name: "BLASRS_External"
    ports:
      - "3002:3002"
    environment:
      - TEMPLATE_PATH="/app/server/template/template.xlsx"
      - BROKER_FILE_PATH="/app/server/brokers_submissions"
      - ORACLEDB_USER="CRS"
      - ORACLEDB_PASSWORD="hocus$pocus59"
      - ORACLEDB_CONNECT_STRING="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=sroraprod)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=oraprod)))"
      - DB2_CONNECTION_STRING="REFUQUJBU0UgPSBFU1VTRVJEQjsgSE9TVE5BTUUgPSBTUlRTVERCOyBVSUQgPSBlc3VzZXI7IFBXRCA9IGRiMkBhZG1pbjE7IFBPUlQgPSA1MDAwMzsgUFJPVE9DT0wgPSBUQ1BJUDsgU2VjdXJpdHk9U1NMOyBTU0xDbGllbnRLZXlzdG9yZWRiPUM6XElCTVxTU0xcU0VDUGRic2VydmVyLmtkYjsgU1NMQ2xpZW50S2V5c3Rhc2g9QzpcSUJNXFNTTFxTRUNQZGJzZXJ2ZXIuc3RoOw=="
      - PRIVATE_KEY="sEcp@12345"